replicaCount: 1
image:
  repository: bitnami/rabbitmq
  tag: 3.11
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 5672
  managementPort: 15672
resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "200m"
persistence:
  enabled: true
  storageClass: "standard"
  accessMode: ReadWriteOnce
  size: 8Gi
extraPlugins: "rabbitmq_tracing"
configuration: |  
  listeners.tcp.default = 5672
  management.load_definitions = /app/load_definitions.json
  tracing.enabled = true
  tracing.storage = zipkin
  tracing.zipkin.endpoint = http://zipkin.testing.svc.cluster.local:9411/api/v2/spans
extraEnvVars:
  - name: TRACING_ZIPKIN_HOST
    value: "zipkin.testing.svc.cluster.local"
  - name: TRACING_ZIPKIN_PORT
    value: "9411"
auth:
  username: admin
  password: secretpassword
  erlangCookie: secretcookie
  rabbitmq.username: admin
  rabbitmq.password: secretpassword