apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: vault
  template:
    spec:
      resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 75m
            memory: 128Mi
