apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  template:
    spec:
      containers:
        - name : uptime-kuma
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 75m
              memory: 128Mi
