apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  destination:
    namespace: testing
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://github.com/DanielNugrahaHS/devops-gitops'
    targetRevision: master
    path: kustomize/overlays/dev-vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
spec:
  destination:
    namespace: uptime-kuma
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://github.com/DanielNugrahaHS/devops-gitops'
    targetRevision: master
    path: kustomize/overlays/dev-uptime-kuma
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

