apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/DanielNugrahaHS/devops-gitops' # Ganti dengan URL repo Git Anda
    targetRevision: HEAD
    path: redis
    helm:
      valueFiles:
        - values.yaml # Sesuaikan jika menggunakan nilai yang berbeda
  destination:
    server: https://kubernetes.default.svc
    namespace: testing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
