global:
  name: redis
  namespaceOverride: testing  

master:
  persistence:
    enabled: true
    storageClass: "" 
    size: 4Gi 
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "512Mi"
      cpu: "200m"

replica:
  replicaCount: 1  
  persistence:
    enabled: true
    storageClass: ""  
    size: 4Gi  
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "512Mi"
      cpu: "200m"

networkPolicy:
  enabled: true  

service:
  type: ClusterIP  
  port: 6379
