apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: vault
data:
  config.json: |
    {
      "listener": [
        {
          "tcp": {
            "address": "0.0.0.0:8200",
            "tls_disable": true
          }
        }
      ],
      "ui": true
    }
