apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: vault
data:
  config.json: |
    {
      "ui": true,
      "listener": {
        "tcp": {
          "address": "0.0.0.0:8200",
          "tls_disable": true
        }
      },
      "storage": {
        "file": {
          "path": "/vault/data"
        }
      }
    }
