apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: hashicorp/vault:latest
          args: ["server"]
          ports:
            - containerPort: 8200
          env:
            - name: VAULT_DEV_ROOT_TOKEN_ID
              value: "root"
            - name: VAULT_LOCAL_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: vault-config
                  key: config.json
            - name: VAULT_LOG_LEVEL
              value: "debug"
          volumeMounts:
            - name: config-volume
              mountPath: /vault/config
      volumes:
        - name: config-volume
          configMap:
            name: vault-config
        - name: vault-config-dir
          emptyDir: {}
