apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: hashicorp/vault:latest
          args: ["server", "-dev"]
          ports:
            - containerPort: 8200
          env:
            - name: VAULT_DEV_ROOT_TOKEN_ID
              value: "root"
            - name: VAULT_LOCAL_CONFIG
              value: /vault/config/config.json
            - name: VAULT_LOG_LEVEL
              value: "debug"
          volumeMounts:
            - name: vault-config-dir
              mountPath: /vault/config
            - name: config-volume
              mountPath: /vault/config/config.json
              subPath: config.json
          securityContext:
            capabilities:
              add: ["IPC_LOCK"]
      volumes:
        - name: vault-config-dir
          emptyDir: {}
        - name: config-volume
          configMap:
            name: vault-config
