# templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: Opaque
data:
  username: {{ .Values.auth.username | b64enc }}
  password: {{ .Values.auth.password | b64enc }}
  rabbitmq-erlang-cookie: {{ .Values.auth.erlangCookie | b64enc }}