global:
  name: redis
  namespaceOverride: testing  

serviceAccount:
  create: true

ingress:
  enabled: false

autoscaling:
  enabled: false  # Set ke true jika ingin menggunakan autoscaling
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

image:
  repository: "bitnami/redis"  # Ganti dengan image Redis yang Anda inginkan
  tag: "latest"                # Ganti dengan versi yang sesuai, misalnya "6.2.6"
  pullPolicy: IfNotPresent

master:
  persistence:
    enabled: true
    storageClass: "" 
    size: 4Gi 
  # resources:
  #   requests:
  #     memory: "128Mi"
  #     cpu: "50m"
  #   limits:
  #     memory: "512Mi"
  #     cpu: "200m"

replica:
  replicaCount: 1  
  persistence:
    enabled: true
    storageClass: ""  
    size: 4Gi  
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "512Mi"
      cpu: "200m"

networkPolicy:
  enabled: true  

service:
  type: ClusterIP  
  port: 6379
