global:
  name: redis
  namespaceOverride: testing  # Namespace tempat Redis akan dideploy

master:
  persistence:
    enabled: true
    storageClass: ""  # Kosongkan ini jika ingin menggunakan default storage class dari Minikube
    size: 20Gi  # Ukuran penyimpanan yang diinginkan
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"

replica:
  replicaCount: 1  # Jumlah replica Redis
  persistence:
    enabled: true
    storageClass: ""  # Kosongkan ini jika ingin menggunakan default storage class dari Minikube
    size: 20Gi  # Ukuran penyimpanan yang diinginkan untuk replica juga
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"

networkPolicy:
  enabled: true  # Mengaktifkan NetworkPolicy untuk keamanan jaringan

service:
  type: ClusterIP  # Jenis service Redis
  port: 6379
